#!/bin/bash

#MISE sources=["docker/Dockerfile.base"]
#USAGE arg "v version" "version to tag the image with" {
#USAGE   default "local"
#USAGE }

docker build \
    -t dayzserver:base-${usage_version:-local} \
    --file ./docker/Dockerfile.base \
    --build-arg BUILD_DATE="$(date +%Y-%m-%dT%H:%M:%S)" \
    ./