#!/bin/bash

#MISE sources=["apps/docker/Dockerfile.base"]
#USAGE flag "-v --version <version>" "version to tag the image with" default="local"

docker build \
    -t dayzserver:base-"${usage_version:-local}" \
    --file ./pkgs/docker/Dockerfile \
    --build-arg BUILD_DATE="$(date +%Y-%m-%dT%H:%M:%S)" \
    ./
