#
# These are the shared volumes.
# All server containers will use these volumes.

volumes:
  # For steamcmd files and resource files used by the scripts
  homedir_main:
  # For Steam, for now
  homedir_server:
  # Where the server files will be installed
  serverfiles:
  # Server profile files
  profiles:
  # Upstream mission files
  servermpmissions:
  # Server mission files
  mpmissions:
  # Mods
  mods:

services:
  manager:
    image: dayzserver:manager-${version:-local}
    user: ${USER_ID}
    volumes:
      - homedir_main:/home/user
      - serverfiles:/serverfiles
      - servermpmissions:/serverfiles/mpmissions
      - mods:/serverfiles/steamapps/workshop/content
      - mods:/mods
      - ./files:/files
      - ./:/opt/repo/
    ports:
      - '5173:5173/tcp'
      - '8000:8000/tcp'
    restart: always
    environment:
      - MANAGER_PORT=8000
    env_file:
      - .env
