#
# These are the shared volumes.
# All server containers will use these volumes.

volumes:
  # For steamcmd files and resource files used by the scripts
  # /home/manager
  # /home/:serverid
  homes:

  # Where the server files will be installed
  # Steam downloads dayzserver here
  # /store/steam/DayZServer
  steamstore:

  # Serverfiles
  # /serverfiles/:serverid/DayZServer
  serverstore:

  # Activated Server Mod Store
  # /serverfiles/:serverid/mods/
  serverstoremods:

  # Server Missions
  # /serverfiles/:serverid/mpmissions/
  serverstoremissions:

  # /serverfiles/:serverid/profiles/
  serverstoreprofiles:

services:
  volume_setup:
    image: alpine
    container_name: 'volume_setup'
    command: |
      mkdir -p /home/manager

    volumes:
      - homes:/home

  manager:
    image: dayzserver:manager-${version:-local}
    user: ${USER_ID}
    depends_on:
      - 'volume_setup'
    volumes:
      # only mount the manager home directory
      # - type: volume
      #   source: homes
      #   target: /home/user
      #   volume:
      #     subpath: manager

      - steamstore:/store/steam

      # mount all the server missions
      - serverstore:/store/serverfiles

      # mount all the server missions
      - serverstoremods:/store/servermods

      # mount all the server missions
      - serverstoremissions:/store/servermissions

      # mount all the server missions
      - serverstoreprofiles:/store/serverprofiles

      # stores all our customisations
      - ./files:/store/files

      # these are for development
      - ./:/opt/repo/

    ports:
      - '5173:5173/tcp'
    restart: always
    environment:
      - MANAGER_PORT=8000
