#!/usr/bin/env bash

build_images() {
    local user_id

    user_id=$(id -u)

    docker build \
        --build-arg "USER_ID=${user_id}" \
        --build-arg "VERSION=local" \
        -t "dayzserver:base-local" \
        -f ./pkgs/docker/Dockerfile .

    docker build \
        --build-arg "USER_ID=${user_id}" \
        --build-arg "VERSION=local" \
        -t "dayzserver:server-local" \
        -f ./apps/server/Dockerfile .

    docker build \
        --build-arg "USER_ID=${user_id}" \
        --build-arg "VERSION=local" \
        -t "dayzserver:manager-local" \
        -f ./apps/manager/Dockerfile .

}

install() {
    docker compose run --rm manager mise server:install
}

case "$1" in
images)
    build_images
    ;;
install)
    install
    ;;
*)
    echo "Usage: $0 {images|install}"
    exit 1
    ;;
esac
