export enum Codes {
  ModDownloadError = 'ModDownloadError',
  ModInstallError = 'ModInstallError',
  ModUninstallError = 'ModUninstallError',
  ModFileNotFound = 'ModFileNotFound',
  ModFileFound = 'ModFileFound',
  ModDetailError = 'ModDetailError',
  ModNotFoundError = 'ModNotFoundError',
  ModParsingError = 'ModParsingError',
  ModListError = 'ModListError',
  ModRemoveError = 'ModRemoveError',
  ModUpdateError = 'ModUpdateError',
  ModFileContentsError = 'ModFileContentsError',
  SearchQueryError = 'SearchQueryError',
}
