tasks:
  build:
    command:
      - 'packemon'
      - 'pack'
      - '--addEngines'
      - '--addExports'
      - '--declaration'
      - --formats
      - --debug
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.*.json'

    outputs:
      - 'lib'
