# yaml-language-server: $schema=../cache/schemas/tasks.json
implicitDeps:
  - '^:build'

implicitInputs:
  - 'package.json'

fileGroups:
  # Application specific files
  app: []
  configs:
    - '*.{js,json,yml,yaml}'
  sources:
    - 'public/**/*'
    - 'src/**/*'
    - 'types/**/*'
  tests:
    - 'tests/**/*.test.*'
    - 'tests/**/*.stories.*'
    - '**/__tests__/**/*'
  assets:
    - 'assets/**/*'
    - 'images/**/*'
    - 'static/**/*'
    - '**/*.{scss,css}'
    - '**/*.{md,mdx}'
