export enum ResponseCodes {
  ModInstallSuccess = "ModInstallSuccess",
  ModInstallError = "ModInstallError",
  ModFileNotFound = "ModFileNotFound",
  ModFileFound = "ModFileFound",
  ModListSuccess = "ModListSuccess",
  ModDetailError = "ModDetailError",
  ModDetailSuccess = "ModDetailSuccess",
  ModNotFoundError = "ModNotFoundError",
  ModParsingError = "ModParsingError",
  ModFoundSuccess = "ModFoundSuccess",
  ModListError = "ModListError",
  ModRemovedSuccess = "ModRemovedSuccess",
  ModRemoveError = "ModRemoveError",
  ModUpdateSuccess = "ModUpdateSuccess",
  ModUpdateError = "ModUpdateError",
  ModActivatedSuccess = "ModActivatedSuccess",
  ModActivatedError = "ModActivatedError",
  ModDeactivatedSuccess = "ModDeactivatedSuccess",
  ModDeactivatedError = "ModDeactivatedError",
  ModFileContentsError = "ModFileContentsError",
  SearchQuerySuccess = "SearchQuerySuccess",
  SearchQueryError = "SearchQueryError",
}
