export enum ResponseCodes {
  ModDownloadSuccess = 'ModDownloadSuccess',
  ModDownloadError = 'ModDownloadError',
  ModInstallSuccess = 'ModInstallSuccess',
  ModInstallError = 'ModInstallError',
  ModUninstallSuccess = 'ModUninstallSuccess',
  ModUninstallError = 'ModUninstallError',
  ModFileNotFound = 'ModFileNotFound',
  ModFileFound = 'ModFileFound',
  ModListSuccess = 'ModListSuccess',
  ServerModListSuccess = 'ServerModListSuccess',
  ModDetailError = 'ModDetailError',
  ModDetailSuccess = 'ModDetailSuccess',
  ModNotFoundError = 'ModNotFoundError',
  ModParsingError = 'ModParsingError',
  ModFoundSuccess = 'ModFoundSuccess',
  ModListError = 'ModListError',
  ModRemovedSuccess = 'ModRemovedSuccess',
  ModRemoveError = 'ModRemoveError',
  ModUpdateSuccess = 'ModUpdateSuccess',
  ModUpdateError = 'ModUpdateError',
  ModFileContentsError = 'ModFileContentsError',
  SearchQuerySuccess = 'SearchQuerySuccess',
  SearchQueryError = 'SearchQueryError',
}
